### ISSUE TITLE
API Key wont link

### ISSUE THREAD

**Issue by bankaiii** [humhub-contrib/notes#10]
Hi Luke
Thanks for your work on this module.

After installed and test etherpad lite - I try to put my api key generated after the install but humhub say "Can't connect to API".
Where I can find more information logs to give you more details about my issue ?
Do you have a tricks ?

I setup etherpad lite on the same machine ubuntu 14.04 with humhub ( nginx + ssl + mariaDb + Nodejs ppa ).

Best regards
Bankaiiii

**Comment by Wachhund** [comment]
same problem here.

I see, there is no try to acccess the pad.
So the module doesnt sending out any requests.

**Comment by bigdriveca** [comment]
Having the same issue here. "Can't connect to API". I can hit my pads from the outside at:
http://pad.fintraks.com/pad/ but when I put that link into the Etherpad module configuration along with my API key from within HumHub, it won't connect to the API. Is it a 127.0.0.1 thing?

**Comment by stefanschauer** [comment]
I needed to add a slash after the url
