### ISSUE TITLE
"You do not have permission to access this pad" issue with Notes in space with connected etherpad API

### ISSUE THREAD

**Issue by petrk94** [humhub-contrib/notes#22]
Hello Humhub Team,

I want to save a note in a space, but it doesnt work.
Instead of working, I get "You do not have permission to access this pad", but the API got successfully connected to: http://pad.xxxxxx.de:9001

I hope you can help
![humhub_notes](https://user-images.githubusercontent.com/19719052/40541749-6acb0b98-601d-11e8-92cd-4c621ddfb763.PNG)

**Comment by Joe1am** [comment]
I have the same problem.. any ideas?
