### ISSUE TITLE
Error opening the note

### ISSUE THREAD

**Issue by m4rt1nm0r** [humhub-contrib/notes#27]
I can create a note. But I can't open it, it returns the following error:

yii\base\UnknownMethodException: Calling unknown method: humhub\modules\content\models\Content::canRead() in /var/www/humhub/protected/vendor/yiisoft/yii2/base/Component.php:300 Stack trace: #0 /var/www/humhub/protected/modules/notes/controllers/NoteController.php(74): yii\base\Component->__call('canRead', Array) #1 [internal function]: humhub\modules\notes\controllers\NoteController->actionOpen() #2 /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #3 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #4 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('open', Array) #5 /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('notes/note/open', Array) #6 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #7 /var/www/humhub/index.php(25): yii\base\Application->run() #8 {main}

**Comment by luke-** [comment]
Which HUmHub version are you using?

**Comment by m4rt1nm0r** [comment]
> 
> 
> Which HUmHub version are you using? 

1.4.0-beta.1 (thank you, luke).

I have been able to solve the problem. 
canRead() is deprecated. I use canView method instead, in NoteController.php(74)

Now it works fine.
-- | --
