### ISSUE TITLE
Bug: No space allowed in tables

### ISSUE THREAD

**Issue by Meeques** [humhub-contrib/notes#34]
Hi!
When I create a table and then write into a cell, there are no spaces allowed (space gets deleted right after typing). The only option is to type the following character first, then insert space after. For example type "cell1", then go back and insert space to create "cell 1"
Thanks!

**Comment by luke-** [comment]
This is probably a problem with the Etherpad editor then, isn't it? 

We integrate this editor only with the Notes module.

**Comment by Meeques** [comment]
@luke-  Yes! I thought this was the repository. Do you know where I can submit issues regarding etherpad notes module?

**Comment by luke-** [comment]
That is correct here. Only probably this is more an Etherpad problem and not a problem with the Etherpad integration module :-)

**Comment by Meeques** [comment]
Oh, got it. Thanks :)
